services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development 
    stdin_open: true 
    tty: true
    command: ["npm", "run", "start"]
